// Prisma Client
// This file will be generated by Prisma

import { PrismaClient } from "@prisma/client"

const globalForPrisma = globalThis as unknown as {
  prisma: PrismaClient | undefined
}

// Fix for connection pooling issues - ensure singleton pattern
// Note: Prepared statement conflicts are handled via retry logic in prisma-helper.ts
export const prisma =
  globalForPrisma.prisma ??
  new PrismaClient({
    log: process.env.NODE_ENV === "development" ? ["error", "warn"] : ["error"],
  })

// Always use singleton in production to avoid connection issues
if (process.env.NODE_ENV !== "production") {
  globalForPrisma.prisma = prisma
} else {
  // In production, ensure we don't create multiple instances
  globalForPrisma.prisma = prisma
}

// Cleanup on process termination
if (process.env.NODE_ENV !== "production") {
  process.on('beforeExit', async () => {
    await prisma.$disconnect()
  })
}
